controller_frequency: 3
recovery_behaviour_enabled: true

TrajectoryPlannerROS:
  max_vel_x: 0.5 #0.5
  min_vel_x: 0.01 #0.01
  max_vel_theta: 1.5 #1.5

  min_in_place_vel_theta: 0.314

  acc_lim_theta: 3.14
  acc_lim_x: 2.0
  acc_lim_y: 2.0

  sim_time: 1.0

  vx_samples: 5.0
  vtheta_samples: 10.0

  pdist_scale: 0.6 #0.6
  gdist_scale: 0.8 #0.8
  occdist_scale: 0.09 ***

  holonomic_robot: false

  meter_scoring: true
  heading_lookahead: 0.325  #How far to look ahead in meters when scoring different in-place-rotation trajectories
  heading_scoring_timestep: 0.9   #How far to look ahead in time ...

  holonomic_robot: false

